name: Xcode - Build and test project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Unit tests
    runs-on: macos-12
    env:
      SOURCE_PACKAGES_PATH: .spm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.2'

      - name: Run tests
        run: |
          xcodebuild clean build test CODE_SIGNING_REQUIRED=NO -project Glass-Fit/Glass-Fit.xcodeproj -scheme Glass-Fit -destination 'platform=iOS Simulator,name=iPhone 8 Plus,OS=16.2' -configuration Debug